config:
    paths:
        'orohangoutscall/js/app/components/invite-hangout-component': 'bundles/oroothercall/js/app/components/invite-hangout-component.js'
        'orohangoutscall/js/app/components/calendar-event-start-hangout-component': 'bundles/oroothercall/js/app/components/calendar-event-start-hangout-component.js'
        'orohangoutscall/js/app/components/log-call-component': 'bundles/oroothercall/js/app/components/log-call-component.js'
build:
    paths:
        '//apis.google.com/js/platform.js': 'empty:'
