parameters:
    oro_other_call.placeholder.filter.class: Oro\Bundle\OtherCallBundle\Placeholder\PlaceholderFilter
    oro_other_call.placeholder.calendar_event.filter.class: Oro\Bundle\OtherCallBundle\Placeholder\CalendarEventPlaceholderFilter
    oro_other_call.placeholder.call.filter.class: Oro\Bundle\OtherCallBundle\Placeholder\CallPlaceholderFilter
    oro_other_call.type.use_other_checkbox.class: Oro\Bundle\OtherCallBundle\Form\UseOtherCheckboxType

services:
    oro_other_call.placeholder.filter:
        class: '%oro_other_call.placeholder.filter.class%'
        arguments:
            - '@oro_config.user'
            - '@oro_ui.user_agent_provider'
    oro_other_call.placeholder.calendar_event.filter:
        class: '%oro_other_call.placeholder.calendar_event.filter.class%'
        arguments:
            - '@oro_other_call.placeholder.filter'
            - '@oro_entity.doctrine_helper'
            - '@oro_security.token_accessor'
    oro_other_call.placeholder.call.filter:
        class: '%oro_other_call.placeholder.call.filter.class%'
        arguments:
            - '@oro_other_call.placeholder.filter'
            - '@oro_entity.doctrine_helper'
    oro_other_call.twig.othercall_extension:
        class: Oro\Bundle\OtherCallBundle\Twig\OroOtherCallExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }
    oro_other_call.type.use_other_checkbox:
        class: '%oro_other_call.type.use_other_checkbox.class%'
        tags:
            - { name: form.type, alias: oro_other_call_use_other_checkbox_type }
