placeholders:
    placeholders:
        requirejs_config_extend:
            items:
                oro_othercall_requirejs_config:
                    order: 110
        email_actions:
            items:
                oro_othercall_email_action_button:
                    order: 10
        phone_actions:
            items:
                oro_othercall_phone_action_button:
                    order: 10
        calendar_event_widget_view_additional_properties:
            items:
                oro_othercall_calendar_event_widget_view_additional_properties:
                    order: 10
        call_log_widget_additional_properties:
            items:
                oro_othercall_call_log_widget_additional_properties:
                    order: 10
        view_navButtons_after:
            items:
                oro_othercall_calendar_event_view_actions:
                    order: 10
        update_navButtons_after:
            items:
                oro_othercall_call_log_update_actions:
                    order: 10

    items:
        oro_othercall_requirejs_config:
            template: OroOtherCallBundle::requirejs.config.js.twig
        oro_othercall_email_action_button:
            applicable: "@oro_other_call.placeholder.filter->isEmailApplicable()"
            template: OroOtherCallBundle:Call/action:inviteOtherButton.html.twig
        oro_othercall_phone_action_button:
            applicable: "@oro_other_call.placeholder.filter->isPhoneApplicable()"
            template: OroOtherCallBundle:Call/action:inviteOtherButton.html.twig
        oro_othercall_calendar_event_widget_view_additional_properties:
            applicable: "@oro_other_call.placeholder.filter->isEmailApplicable()"
            template: OroOtherCallBundle:CalendarEvent/widget:additionalProperties.html.twig
        oro_othercall_calendar_event_view_actions:
            applicable: "@oro_other_call.placeholder.calendar_event.filter->isApplicable($entity$)"
            template: OroOtherCallBundle:CalendarEvent:viewActions.html.twig
        oro_othercall_call_log_widget_additional_properties:
            applicable: "@oro_other_call.placeholder.filter->isPhoneApplicable()"
            template: OroOtherCallBundle:Call/widget:additionalProperties.html.twig
        oro_othercall_call_log_update_actions:
            applicable: "@oro_other_call.placeholder.call.filter->isApplicable($entity$)"
            template: OroOtherCallBundle:Call:updateActions.html.twig
