system_configuration:
    groups:
        google_other_settings:
            title: oro.othercall.system_configuration.groups.google_other_settings.title

    fields:
        oro_other_call.enable_google_other_for_email:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.othercall.system_configuration.fields.enable_google_other_for_email.label
                required: false
                resettable: true
            priority: 40
        oro_other_call.enable_google_other_for_phone:
              data_type: boolean
              type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
              options:
                  label: oro.othercall.system_configuration.fields.enable_google_other_for_phone.label
                  required: false
                  resettable: true
              priority: 40

    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            google_settings:
                                children:
                                    google_other_settings:
                                        children:
                                            - oro_other_call.enable_google_other_for_email
                                            - oro_other_call.enable_google_other_for_phone
        organization_configuration:
            platform:
                children:
                    integrations:
                        children:
                            google_settings:
                                children:
                                    google_other_settings:
                                        children:
                                            - oro_other_call.enable_google_other_for_email
                                            - oro_other_call.enable_google_other_for_phone
